[package]
name = "mpeg2ts-reader-shootout"
version = "0.0.1"
publish = false
edition = "2021"

[dependencies]
mpeg2ts = "0.1.1"
mpeg2ts-reader = { path = ".." }
ffmpeg-sys-next = "7.1.0"

[dev-dependencies]
criterion = "0.2"

[[bench]]
name = "bench"
harness = false
